stop publish if version is empty

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -32,6 +32,11 @@ jobs:
       - name: Deploy to Sonatype
         run: |
           NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
+          if [ -z "$NEW_VERSION" ]; then
+            echo "ERROR: Version is empty"
+            echo "GITHUB_REF: ${GITHUB_REF}"
+            exit 1
+          fi
           echo "New version: ${NEW_VERSION}"
           export ORG_GRADLE_PROJECT_VERSION_NAME=${NEW_VERSION}
           echo "RELEASE_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
